name: scpfiles
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: copy files
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.FANTOM_HOST }}
          username: ${{ secrets.FANTOM_USERNAME }}
          port: ${{ secrets.FANTOM_PORT }}
          key: ${{ secrets.FANTOM_KEY }}
          source: "source/en.json"
          target: "/tmp/test"
