name: move translate files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy files
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.FANTOM_HOST }}
          username: ${{ secrets.FANTOM_USERNAME }}
          password: ${{ secrets.FANTOM_PASS }}
          port: ${{ secrets.FANTOM_PORT }}
          source: "source/en.json"
          target: "/tmp/test"
